let Place = function (args) {
    this.name = args.name;
    this.type = args.type; // 'citadel', 'polis', or 'wilderness'
    this.borderNames = args.borderNames; // Names of adjacent places
    this.nation = args.nation; // Hellas, Anatolia, Crete
    this.adjectives = args.adjectives; // "rich", "rocky"
    this.epithets = args.epithets; // "beloved of Helios"
}

game.data.map = {
    'Mycenae': new Place ({
        name: 'Mycenae',
        coordinates: {
            x: 9012,
            y: 5025,
        },
        type: 'citadel',
        nation: 'Hellas',
        adjectives: ['mighty', 'great', 'high-walled'],
        epithets: ['the city of lions', 'of the cyclopean walls',],
        borderNames: ['Salamis', 'Corinth'],
    }),
    'Aegina': new Place ({
        name: 'Aegina',
        coordinates: {
            x: 9216,
            y: 5030,
        },
        type: 'polis',
        nation: 'Hellas',
        adjectives: ['trade-busy'],
        epithets: ['of the fast ships'],
        borderNames: ['Salamis', 'Hydrea', 'Sounio'],
    }),
    'Sounio': new Place ({
        name: 'Sounio',
        coordinates: {
            x: 9500,
            y: 5060,
        },
        type: 'polis',
        nation: 'Hellas',
        adjectives: ['salt-caked', 'revered', 'sea-beaten', 'tide-eaten', 'high', 'well-fortified'],
        epithets: ['with its beaches that shine like beaten bronze', 'sitting between water and land', 'sacred to the king of tides', 'sacred to the lord of horses', 'sacred to the earthshaker', 'sentinel of the coast', 'at Attika\'s point', 'at Attika\'s point'],
        borderNames: ['Aegina', 'Thebes'],
    }),
    'Salamis': new Place ({
        name: 'Salamis',
        coordinates: {
            x: 9204,
            y: 4881,
        },
        type: 'polis',
        nation: 'Hellas',
        adjectives: ['fertile', 'quiet'],
        epithets: ['the wooded island'],
        borderNames: ['Aegina', 'Mycenae'],
    }),
    'Corinth': new Place ({
        name: 'Corinth',
        coordinates: {
            x: 8914,
            y: 4865,
        },
        type: 'polis',
        nation: 'Hellas',
        adjectives: ['rich'],
        epithets: ['city of merchants', 'the city between seas'],
        borderNames: ['Mycenae', 'Delphi'],
    }),
    'Hydrea': new Place ({
        name: 'Hydrea',
        coordinates: {
            x: 9176,
            y: 5300,
        },
        type: 'polis',
        nation: 'Hellas',
        adjectives: ['fresh-flowing'],
        epithets: ['rich in springwater'],
        borderNames: ['Mycenae', 'Argos'],
    }),
    'Thebes': new Place (
        name: 'Thebes',
        coordinates: {
            x: 9476,
            y: 4800,
        },
        type: 'citadel',
        nation: 'Hellas',
        adjectives: ['seven-gated'],
        epithets: ['heavy-burdened by the Fates', 'city of the dragon\'s teeth'],
        borderNames: ['Chios', 'Mykonos', 'Aulis', 'Sounio'],
    }),
    'Delphi': new Place ({
        name: 'Delphi',
        coordinates: {
            x: 8360,
            y: 4520,
        },
        type: 'polis',
        nation: 'Hellas',
        adjectives: ['blessed'],
        epithets: ['where Apollo slew Python', 'sacred to Apollo', 'sacred to wolf-born Apollo'],
        borderNames: ['Corinth', 'Ithaka'],
    }),
    'Argos': new Place ({
        name: 'Argos',
        coordinates: {
            x: 8855,
            y: 5144,
        },
        type: 'citadel',
        nation: 'Hellas',
        adjectives: ['strong-walled', 'abundant'],
        epithets: ['the cradle of heroes', 'beloved of Hera', 'beloved by the queen of Olympus'],
        borderNames: ['Hydrea', 'Arkadia'],
    }),
    'Chios': new Place ({
        name: 'Chios',
        coordinates: {
            x: 10378,
            y: 4574,
        },
        type: 'polis',
        nation: 'Anatolia',
        adjectives: ['wine-rich', 'shaded'],
        epithets: ['the island of pine trees', 'the sphinx-isle'],
        borderNames: ['Thebes', 'Ephesus', 'Smyrna'],
    }),
    'Mykonos': new Place ({
        name: 'Mykonos',
        coordinates: {
            x: 10080,
            y: 5225,
        },
        type: 'polis',
        nation: 'Hellas',
        adjectives: ['boulder-strewn', 'granite-cliffed'],
        epithets: ['the island of the giants\' defeat', 'where Zeus struck down the last giants'],
        borderNames: ['Thebes', 'Delos', 'Ikaria'],
    }),
    'Aulis': new Place ({
        name: 'Aulis',
        coordinates: {
            x: 9355,
            y: 974,
        },
        type: 'polis',
        nation: 'Hellas',
        adjectives: ['broad-harbored', 'small', 'windless'],
        epithets: ['on the shore'],
        borderNames: ['Thebes', 'Phthia'],
    }),
    'Ithaka': new Place ({
        name: 'Ithaka',
        coordinates: {
            x: 7720,
            y: 4530,
        },
        type: 'polis',
        nation: 'Hellas',
        adjectives: ['rocky', 'far-sailing'],
        epithets: ['city of explorers', 'city of navigators', 'city of ships'],
        borderNames: ['Delphi', 'Olympia', 'Syrakuse'],
    }),
    'Arkadia': new Place ({
        name: 'Arkadia',
        coordinates: {
            x: 8938,
            y: 5528,
        },
        type: 'polis',
        nation: 'Hellas',
        adjectives: ['wild', 'untamed'],
        epithets: ['at the edge of the wilderness', 'at the edge of the forests'],
        borderNames: ['Argos', 'Milos', 'Kythera'],
    }),
    'Ephesus': new Place ({
        name: 'Ephesus',
        coordinates: {
            x: 10970,
            y: 4826,
        },
        type: 'polis',
        nation: 'Anatolia',
        adjectives: ['prosperous', 'open-harbored'],
        epithets: ['beloved of Artemis', 'sacred to the huntress', 'sacred to the moon goddess'],
        borderNames: ['Chios', 'Samos', 'Miletos'],
    }),
    'Smyrna': new Place ({
        name: 'Smyrna',
        coordinates: {
            x: 10976,
            y: 4556,
        },
        type: 'polis',
        nation: 'Anatolia',
        adjectives: ['myrrh-rich', 'thorn-thick'],
        epithets: ['by the river Meles', 'blessed by rivers'],
        borderNames: ['Chios', 'Lesbos'],
    }),
    'Delos': new Place ({
        name: 'Delos',
        coordinates: {
            x: 9908,
            y: 5315,
        },
        type: 'polis',
        nation: 'Hellas',
        adjectives: ['sacred', 'barren', 'tiny'],
        epithets: ['the holy island', 'the sanctuary island', 'place of gods\' birth'],
        borderNames: ['Milos', 'Mykonos'],
    }),
    'Ikaria': new Place ({
        name: 'Ikaria',
        coordinates: {
            x: 10400,
            y: 5800,
        },
        type: 'polis',
        nation: 'Hellas',
        adjectives: ['red', 'cliff-walled', 'salt-beaten'],
        epithets: ['island of brine and crabs', 'island of sharp rocks'],
        borderNames: ['Mykonos', 'Samos', 'Patmos', 'Naxos'],
    }),
    'Phthia': new Place ({
        name: 'Phthia',
        coordinates: {
            x: 8972,
            y: 4334,
        },
        type: 'polis',
        nation: 'Hellas',
        adjectives: ['fertile', 'sea-blessed'],
        epithets: ['at the mouth of the river Sperkheios', 'home of the strong-greaved Myrmidones', 'home of the Myrmidones'],
        borderNames: ['Aulis', 'Iolkos'],
    }),
    'Olympia': new Place ({
        name: 'Olympia',
        coordinates: {
            x: 8090,
            y: 5102,
        },
        type: 'polis',
        nation: 'Hellas',
        adjectives: ['glorious', 'high'],
        epithets: ['beloved by the son of Kronos', 'beloved of Zeus', 'of the great games'],
        borderNames: ['Pylos', 'Ithaka'],
    }),
    'Syrakuse': new Place ({
        name: 'Syrakuse',
        coordinates: {
            x: 8,
            y: 4,
        },
        type: 'polis',
        nation: 'Hellas',
        adjectives: ['far-flung', 'distant', 'high-towered'],
        epithets: ['in the shadow of Aetna', 'on the Cyclopean shores', 'the gateway to the divine wild', 'the gateway to the monstrous wild', 'the western colony'],
        borderNames: ['Ithaka'],
    }),
    'Milos': new Place ({
        name: 'Milos',
        coordinates: {
            x: 12830,
            y: 9508,
        },
        type: 'polis',
        nation: 'Hellas',
        adjectives: ['beautiful', 'volcanic', 'lava-bathed', 'shining black'],
        epithets: ['beloved of the Muses', 'home of great craftsmen', 'home of artists'],
        borderNames: ['Arkadia', 'Akrotiri', 'Delos'],
    }),
    'Kythera': new Place ({
        name: 'Kythera',
        coordinates: {
            x: 8912,
            y: 6077,
        },
        type: 'polis',
        nation: 'Hellas',
        adjectives: ['trade-rich', 'deep-harbored'],
        epithets: ['beloved of Aphrodite', 'island of sailors', 'rich in purple dye'],
        borderNames: ['Sparta', 'Arkadia', 'Cydonia'],
    }),
    'Samos': new Place ({
        name: 'Samos',
        coordinates: {
            x: 10736,
            y: 1350,
        },
        type: 'polis',
        nation: 'Anatolia',
        adjectives: ['rich', 'wine-rich'],
        epithets: ['island of vineyards', 'the island of red clay', 'beloved by the daughter of Kronos', 'beloved by the queen of Olympus'],
        borderNames: ['Ikaria', 'Ephesus'],
    }),
    'Miletos': new Place ({
        name: 'Miletos',
        coordinates: {
            x: 11000,
            y: 5160,
        },
        type: 'polis',
        nation: 'Anatolia',
        adjectives: ['often-conquered', 'river-flooded', 'sun-beaten'],
        epithets: ['at the mouth of the Meander', 'in the land of caves and springs'],
        borderNames: ['Ikaria', 'Ephesus'],
    }),
    'Lesbos': new Place ({
        name: 'Lesbos',
        coordinates: {
            x: 10490,
            y: 4060,
        },
        type: 'polis',
        nation: 'Anatolia',
        adjectives: ['forested', 'mountainous', 'green', 'fruit-rich'],
        epithets: ['home of poets', 'beloved of the Muses', 'island of the petrified forest', 'island of hot springs'],
        borderNames: ['Smyrna', 'Skyros', 'Troy'],
    }),
    'Naxos': new Place ({
        name: 'Naxos',
        coordinates: {
            x: 10202,
            y: 5465,
        },
        type: 'polis',
        nation: 'Hellas',
        adjectives: ['divine', 'bountiful'],
        epithets: ['island of refuge', 'protected by Dionysus', 'protected by the son of Semele'],
        borderNames: ['Akrotiri', 'Ikaria'],
    }),
    'Patmos': new Place ({
        name: 'Patmos',
        coordinates: {
            x: 10676,
            y: 5270,
        },
        type: 'polis',
        nation: 'Hellas',
        adjectives: ['rocky', 'lonely'],
        epithets: ['raised above the waves by Artemis', 'raised above the waves by Leto\'s daughter', 'island of hermits'],
        borderNames: ['Ikaria', 'Miletos', 'Astypalaia'],
    }),
    'Iolkos': new Place ({
        name: 'Iolkos',
        coordinates: {
            x: 8795,
            y: 4070,
        },
        type: 'polis',
        nation: 'Hellas',
        adjectives: ['sturdy-built', 'spacious'],
        epithets: ['city of steadfast warriors', 'rich in flocks'],
        borderNames: ['Phthia', 'Skyros'],
    }),
    'Pylos': new Place ({
        name: 'Pylos',
        coordinates: {
            x: 8200,
            y: 5608,
        },
        type: 'polis',
        nation: 'Hellas',
        adjectives: ['sandy'],
        epithets: ['city of strong walls', 'the deep-harbored city'],
        borderNames: ['Olympia', 'Sparta'],
    }),
    'Akrotiri': new Place ({
        name: 'Akrotiri',
        coordinates: {
            x: 10270,
            y: 5950,
        },
        type: 'polis',
        nation: 'Crete',
        adjectives: ['copper-rich', 'volatile', 'beautiful'],
        epithets: ['city of merchants', 'of the circular harbor', 'island of sparse grapes'],
        borderNames: ['Naxos', 'Milos', 'Astypalaia', 'Knossos'],
    }),
    'Sparta': new Place ({
        name: 'Sparta',
        coordinates: {
            x: 8500,
            y: 5608,
        },
        type: 'polis',
        nation: 'Hellas',
        adjectives: ['warlike'],
        epithets: ['lying low among the hills',],
        borderNames: ['Pylos', 'Kythera'],
    }),
    'Cydonia': new Place ({
        name: 'Cydonia',
        coordinates: {
            x: 9412,
            y: 6512,
        },
        type: 'polis',
        nation: 'Hellas',
        adjectives: ['gold-rich', 'cave-riddled'],
        epithets: ['city of potters and craftsmen', 'city rich in crafts', 'on the island of the bull'],
        borderNames: ['Knossos', 'Kythera'],
    }),
    'Skyros': new Place ({
        name: 'Skyros',
        coordinates: {
            x: 9832,
            y: 4240,
        },
        type: 'polis',
        nation: 'Hellas',
        adjectives: ['bare', 'stony'],
        epithets: ['island of wild horses'],
        borderNames: ['Iolkos', 'Athos', 'Lesbos'],
    }),
    'Lemnos': new Place ({
        name: 'Lemnos',
        coordinates: {
            x: 9977,
            y: 3642,
        },
        type: 'polis',
        nation: 'Anatolia',
        adjectives: ['sheep-rich', 'once-fiery'],
        epithets: ['sacred to the smith of Olympus', 'sacred to the god of fire', 'blessed by smith-god'],
        borderNames: [Athos', 'Troy'],
    }),
    'Troy': new Place ({
        name: 'Troy',
        coordinates: {
            x: 10488,
            y: 3536,
        },
        type: 'citadel',
        nation: 'Anatolia',
        adjectives: ['shining', 'towering', 'impenetrable', 'great', 'mighty'],
        epithets: ['by the river Scamander', 'greatest of all the Aegean cities', 'the citadel built by the gods', 'at the mouth of the fiery Hellespont', 'whose walls flash with the bronze light of the sun'],
        borderNames: [Ismara', 'Lemnos', 'Lesbos'],
    }),
    'Astypalaia': new Place ({
        name: 'Astypalaia',
        coordinates: {
            x: 10652,
            y: 5752,
        },
        type: 'polis',
        nation: 'Crete',
        adjectives: ['pebbly-beached', 'quiet', 'Cretian'],
        epithets: ['beloved by the god of the salty seas', 'with its salty cliffs', 'with its salty cliffs', 'beloved by the god of the deep'],
        borderNames: ['Patmos, 'Akrotiri', 'Rhodes'],
    }),
    'Knossos': new Place ({
        name: 'Knossos',
        coordinates: {
            x: 10400,
            y: 6640,
        },
        type: 'citadel',
        nation: 'Crete',
        adjectives: ['high-towering', 'riddle-crafted', 'royal', 'mighty', 'most ancient', 'rock-cut', 'cliff-hewn', 'wave-beaten', 'ocean-ruling', 'ocean-ruling'],
        epithets: ['the city of secrets', 'on the island of hidden caves', 'on the island of hidden caves', 'the citadel built atop the hidden caves', 'whose beaches flash with the bronze light of the sun', 'on the island of the bull', 'on the island of the bull', 'the oldest of the Aegean cities', 'the first of the Aegean cities', 'city of the first Aegean kings', 'city of ancient conquests', 'the Cretian capital', 'the Cretian capital'],
        borderNames: ['Akrotiri', 'Cydonia', 'Rhodes'],
    }),
    'Athos': new Place ({
        name: 'Athos',
        coordinates: {
            x: 9595,
            y: 3424,
        },
        type: 'polis',
        nation: 'Hellas',
        adjectives: ['quiet', 'holy', 'leafy', 'cold'],
        epithets: ['on the giant\'s carcass', 'of the shaded olive groves', 'on the mountain\'s side', 'thrust out over the wine dark sea'],
        borderNames: ['Thasos', 'Lemnos', 'Skyros'],
    }),
    'Ismara': new Place ({
        name: 'Ismara',
        coordinates: {
            x: 10208,
            y: 2936,
        },
        type: 'polis',
        nation: 'Thrace',
        adjectives: ['snowy', 'Thracian'],
        epithets: ['city of the Cicones', 'the city of the Cicones', 'on the northern shore', 'among the pine trees', 'beside the dark forests'],
        borderNames: ['Thasos', 'Troy'],
    }),
    'Thasos': new Place ({
        name: 'Thasos',
        coordinates: {
            x: 9744,
            y: 3088,
        },
        type: 'polis',
        nation: 'Thrace',
        adjectives: ['cold', 'still-wild', 'pine-choked'],
        epithets: ['by the northern shore', 'by the cold endless forests of the north'],
        borderNames: ['Athos', 'Ismara'],
    }),
}
